export { PACKAGE_NAME, VERSION } from "./constants.js";
export { runCli } from "./cli/run.js";
export {
  type AtlasConfig,
  ConfigError,
  type DetailLevel,
  type LogLevel,
  loadConfig,
  type VisionProviderName,
  validateProviderConfig,
} from "./config.js";
export {
  createVisionProvider,
  OpenAICompatibleProvider,
  ProviderError,
  type CompareImagesInput as ProviderCompareImagesInput,
  type EncodedImage,
  type FetchFn,
  type ProviderErrorCode,
  type ProviderHealth,
  type RawVisionResult,
  type VisionProvider,
  VISION_SYSTEM_PROMPT,
} from "./providers/index.js";
export {
  detectMimeType,
  ImageError,
  type ImageErrorCode,
  type LoadedImage,
  maxImageBytes,
  readImageFromPath,
  type ReadImageOptions,
  SUPPORTED_MIME_TYPES,
  type SupportedMimeType,
  toEncodedImage,
} from "./image/index.js";
export {
  analyzeImage,
  ANALYZE_IMAGE_TOOL_DESCRIPTION,
  ANALYZE_IMAGE_TOOL_NAME,
  type AnalyzeImageDependencies,
  type AnalyzeImageResult,
} from "./tools/analyze-image.js";
export {
  ocrImage,
  OCR_IMAGE_TOOL_DESCRIPTION,
  OCR_IMAGE_TOOL_NAME,
  type OcrImageDependencies,
  type OcrImageResult,
} from "./tools/ocr-image.js";
export {
  analyzeClipboard,
  ANALYZE_CLIPBOARD_TOOL_DESCRIPTION,
  ANALYZE_CLIPBOARD_TOOL_NAME,
  analyzeUiClipboard,
  ANALYZE_UI_CLIPBOARD_TOOL_DESCRIPTION,
  ANALYZE_UI_CLIPBOARD_TOOL_NAME,
  ClipboardImageError,
  diagnoseClipboard,
  DIAGNOSE_CLIPBOARD_TOOL_DESCRIPTION,
  DIAGNOSE_CLIPBOARD_TOOL_NAME,
  OCR_CLIPBOARD_TOOL_DESCRIPTION,
  OCR_CLIPBOARD_TOOL_NAME,
  ocrClipboard,
  type AnalyzeClipboardDependencies,
  type AnalyzeUiClipboardDependencies,
  type DiagnoseClipboardDependencies,
  type OcrClipboardDependencies,
} from "./tools/clipboard.js";
export {
  analyzeUiScreenshot,
  ANALYZE_UI_SCREENSHOT_TOOL_DESCRIPTION,
  ANALYZE_UI_SCREENSHOT_TOOL_NAME,
  type AnalyzeUiScreenshotDependencies,
  type AnalyzeUiScreenshotResult,
} from "./tools/analyze-ui-screenshot.js";
export {
  compareImages,
  COMPARE_IMAGES_TOOL_DESCRIPTION,
  COMPARE_IMAGES_TOOL_NAME,
  type CompareImagesDependencies,
  type CompareImagesResult,
} from "./tools/compare-images.js";
export {
  type AnalyzeImageInput,
  type AnalyzeImageOutput,
  analyzeImageInputSchema,
  analyzeImageOutputSchema,
  type OcrImageInput,
  type OcrImageOutput,
  ocrImageInputSchema,
  ocrImageOutputSchema,
  type AnalyzeClipboardInput,
  type AnalyzeUiClipboardInput,
  type DiagnoseClipboardInput,
  type OcrClipboardInput,
  analyzeClipboardInputSchema,
  analyzeUiClipboardInputSchema,
  diagnoseClipboardInputSchema,
  ocrClipboardInputSchema,
  type AnalyzeUiScreenshotInput,
  type AnalyzeUiScreenshotOutput,
  analyzeUiScreenshotInputSchema,
  analyzeUiScreenshotOutputSchema,
  type CompareImagesInput,
  type CompareImagesOutput,
  compareImagesInputSchema,
  compareImagesOutputSchema,
  normalizeAnalyzeImageOutput,
  normalizeCompareImagesOutput,
  normalizeOcrImageOutput,
  normalizeUiScreenshotOutput,
  renderAnalyzeImageMarkdown,
  renderCompareImagesMarkdown,
  renderOcrImageMarkdown,
  renderUiScreenshotMarkdown,
} from "./extraction/index.js";
export {
  analyzeClipboardMcpInputSchema,
  analyzeImageMcpInputSchema,
  analyzeUiClipboardMcpInputSchema,
  analyzeUiScreenshotMcpInputSchema,
  compareImagesMcpInputSchema,
  diagnoseClipboardMcpInputSchema,
  ocrClipboardMcpInputSchema,
  type AtlasServerDependencies,
  connectAtlasMcpServer,
  createAtlasMcpServer,
  ocrImageMcpInputSchema,
  registerAnalyzeClipboardTool,
  registerAnalyzeImageTool,
  registerAnalyzeUiClipboardTool,
  registerAnalyzeUiScreenshotTool,
  registerCompareImagesTool,
  registerDiagnoseClipboardTool,
  registerOcrClipboardTool,
  registerOcrImageTool,
  serveStdio,
} from "./server.js";
export {
  assertPathAllowed,
  assessPromptInjection,
  PathPolicyError,
  redactSecrets,
  sanitizeAnalyzeOutput,
  sanitizeOcrOutput,
  tagUntrustedText,
} from "./security/index.js";
export {
  interceptImagesForTextModel,
  type InterceptImagesDependencies,
  type InterceptImagesInput,
  type InterceptImagesOptions,
  type InterceptImagesResult,
  executeVisionCall,
  type ExecuteVisionCallDependencies,
  type ExecuteVisionCallResult,
  buildInterceptMessageText,
  collectImagePathsFromPrompt,
  collectAttachmentPaths,
  detectHookClient,
  extractCapturedImagePath,
  formatUserPromptHookOutput,
  hookEnvFileCandidates,
  loadHookEnv,
  parseDotenv,
  appendSessionImage,
  consumeSessionImages,
  isImageFilePath,
  looksLikeCursorAttachedImage,
  parseCursorPostToolUseInput,
  runCursorCaptureImageHook,
  type HookClient,
  type CursorPostToolUseInput,
  getClipboardDetectMode,
  parseUserPromptHookInput,
  readClipboardImage,
  resolveMainModelRef,
  persistAttachedImages,
  runUserPromptHook,
  scheduleClipboardCleanup,
  shouldAutoDetectClipboard,
  type AttachedImageLike,
  type UserPromptHookAttachment,
  type UserPromptHookInput,
  type UserPromptHookOptions,
  type UserPromptHookResult,
  ENV_CLIPBOARD_DETECT,
} from "./harness/index.js";
export {
  type CapabilitySource,
  type DetectedImage,
  type ImageInterceptInput,
  type ImageInterceptOptions,
  type ImageInterceptPlan,
  type ModelCapabilities,
  type ModelsDevCacheEntry,
  type ModelsDevCatalog,
  type ModelsDevClientOptions,
  type ModelsDevLookupInput,
  type ModelsDevModel,
  type ModelsDevProvider,
  type PlannedVisionCall,
  type VisionCapabilityOverride,
  type VisionToolName,
  MODELS_DEV_DEFAULT_TTL_MS,
  MODELS_DEV_DEFAULT_URL,
  ModelsDevClient,
  VISION_INSTRUCTIONS_PROMPT_DESCRIPTION,
  VISION_INSTRUCTIONS_PROMPT_NAME,
  buildInjectedVisionContext,
  buildVisionInstructionsPrompt,
  createModelsDevClient,
  detectImagesInText,
  getDefaultModelsDevClient,
  getModelCapabilities,
  inferVisionTool,
  messageHasImages,
  parseModelRef,
  planImageIntercept,
  planVisionCalls,
  shouldAutoInterceptVision,
  CacheStore,
  CachedVisionProvider,
  type CacheEntry,
  type CacheStoreOptions,
  type CachedVisionProviderOptions,
  CostTracker,
  CostTrackingVisionProvider,
  type CostEntry,
  type CostTrackerOptions,
  type CostTrackingVisionProviderOptions,
} from "./capabilities/index.js";
